server.port=8084
spring.application.name=loan-service

spring.datasource.url=jdbc:postgresql://localhost:5432/loan_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Springdoc OpenAPI / Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.deepLinking=true
springdoc.swagger-ui.presets=swagger-ui.presets.apis,swagger-ui.SwaggerUIStandalonePreset
